apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    azure:
      secretStorage:
        keyVaultName: full-bulldog
      storage:
        storageAccountName: jxfullbulldog
    chartRepository: http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080
    environmentGitOwner: SkisocksOrg
    gitKind: github
    gitName: github
    gitServer: https://github.com
    provider: aks
    registry: fullbulldog.azurecr.io
  environments:
  - key: dev
    owner: SkisocksOrg
    repository: jx3-azure-akv-cluster
  - key: staging
  - key: production
  ingress:
    domain: 20.70.248.13.nip.io
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  pipelineUser:
    username: SkisocksBot
  repository: nexus
  secretStorage: azurekeyvault
  storage:
  - name: logs
    url: azblob://logs
  vault: {}
  webhook: lighthouse
